### ISSUE TITLE
platformer loading time - on Android we don't use libpng

### ISSUE THREAD

**Issue by codz01** [castle-engine/castle-engine#327]
Hi
i've tried the platformer game , it works fine , but the problem is it take 20 seconds to launch ( the time between clicking play button and the game ) i think its long time especially the main scene in the game is not big 
also i've checked the loading time of the game scene in Castle Game Editor , and it take also 20 seconds to show up .

btw i am using the external libpng which is faster then fpcimage 
and i am using the 32bits verion on windows 7 32bits

**Comment by eugeneloza** [comment]
Try adding LibPng DLL and Zlib DLL to the project folder

**Comment by codz01** [comment]
hi eugeneloza , i am already using theme 
without libpng it take longer time

**Comment by eugeneloza** [comment]
> i am already using theme

Make sure that you have the appropriate bitness of the dll (32 bit LibPng and 32 bit Zlib). Because it takes like 15 seconds to load platformer demo for me without those and 3 with.

**Comment by michaliskambi** [comment]
@codz01 We had a very similar case, with exactly these symptoms, recently on Discord.

With LibPng DLL, and Zlib DLL correctly set up (copied alongside the editor exe, and using correct DLL versions -- 32-bit DLLs for 32-bit applications) the loading time is definitely smaller, around 3 seconds.

But when LibPng cannot be used for some reason, we fallback on much slower FpImage which means platformer takes 15-20 seconds to load. This is large loading time of the design in the editor (if editor lacks correct LibPng DLL + Zlib DLL) and large loading time of the game (if game lacks correct LibPng DLL + Zlib DLL).

Solution:

- Use binary packages for win32 from https://github.com/castle-engine/castle-engine/releases/tag/snapshot . We don't advertise them on the main CGE page, but they are built regularly just like win64 ones. With them, the `castle-editor.exe` is already in the `bin` subdirectory alongside proper DLL files, just use it.

    And build the game using the CGE editor or the CGE command-line tool, not from Lazarus (at least once). It will place the relevant DLL files alongside the game EXE automatically. So the game will have fast loading too.

- If you really want to compile editor yourself, make sure to copy the DLL files yourself, from `tools/build-tool/data/external_libraries/i386-win32` if you create 32-bit binaries. You need to copy them **all** (at least LibPng and Zlib for this issue, but really copy them all, e.g. FreeType is required to load fonts) alongside the editor / game EXE. 

    Although the build tool should copy proper DLL files by itself automatically, so the latter should not be needed.

- It this doesn't help, then please attach the full logs:

    1. after you run CGE editor and open the platformer design with map. The editor log is in `c:/Users/<username>/AppData/Local/castle-editor/castle-editor.log` (the details may vary between Windows versions).

    2. after you run platformer. The editor log is in `c:/Users/<username>/AppData/Local/platformer/platformer.log`.

**Comment by codz01** [comment]
hi , sorry for the delay
thanks michaliskambi for the clarification 
seems CGE doesn't recognize the name (libpng.dll) so i change it to (libpng14-14.dll) and now the loading time becoms only 5 seconds , 
so i think the 20sec was when the game uses fpimage !!

**Comment by eugeneloza** [comment]
Yes, indeed. However, note that on 32-bit system, the correct name of the file is `libpng12.dll` and it's a good idea to use the standard one from `tools\build-tool\data\external_libraries\i386-win32`, as other versions may be buggy. And indeed it's looked up by file name, you may check here for details https://github.com/castle-engine/castle-engine/blob/master/src/images/castleinternalpng_dynamic.inc#L937

**Comment by michaliskambi** [comment]
Happy it is solved :)

To be clear, you should use DLLs provided by CGE in `tools\build-tool\data\external_libraries\i386-win32`, not any other LibPng DLLs from the Internet. Because we test that our versions are compatible :)

- E.g. there are various LibPng versions, and LibPng may sometimes break compatibility. That is why we put version number in the DLL name. CGE right now handles at least libpng 1.2-1.4.

- Other LibPng DLLs from the Internet may have other calling convention (`cdecl` vs `stdcall`). We expect `cdecl` (though it is configurable by `LIBPNG_CDECL` in `src/common_includes/castleconf.inc` ).

**Comment by codz01** [comment]
hi again
i've installed platformer on my phone ( Redmi 8A ) , and the problem of loading time is still exist 
this time when i hit play button it tooks around 70 seconds to launch the game 
does castle engine uses libpng on android platform or fpimage ?

**Comment by michaliskambi** [comment]
On Android we don't use libpng now. And yes, it should be fixed.

**Comment by michaliskambi** [comment]
( Although 70 seconds is really long. Just tested, and it is 20 seconds on my device (Samsung Galaxy Tab A, with GPU = Mali-G71). 20 seconds is still too long (libpng should help), but it's not 70 :) )

**Comment by michaliskambi** [comment]
Fixed in https://github.com/castle-engine/castle-engine/commit/87386a541b3137804096b778a915e1f02553bbb6 :)

I'll also release new APK on https://castle-engine.itch.io/platformer shortly.

**Comment by michaliskambi** [comment]
Loading time on my device now drops from ~20 seconds to 1.7 secs :)

This is measured by doing

```
procedure TStateMenu.ClickPlay(Sender: TObject);
begin
  WritelnLog('TStateMenu.ClickPlay');
  TUIState.Current := StatePlay;
end;
```

in platformer `gamestatemenu.pas`, and now you can look at difference between these 2 logs:

```
09-16 02:21:04.069 28811 31261 I platformer: TStateMenu.ClickPlay
09-16 02:21:05.853 28811 31261 I platformer: Configure platform: Platform1
```

**Comment by codz01** [comment]
i've download the new apk , now the time drops to 3sec , very nice 
thanks for the fix
