### ISSUE TITLE
Minor yet annoying editor issues

### ISSUE THREAD

**Issue by bbrtj** [castle-engine/castle-engine#422]
I've got two very minor issues in the castle-editor which reduce QOL.

- When a label (TCastleLabel) has no Caption and is autosized, hence no size, its position on screen is often reset to 0:0 when changing it or other components. For example changing the anchor position for the label resets its position. I use such empty labels to feed them with content later, although for now I just set some placeholder content inside them which I empty in code.
- I use an unusual keyboard layout, programmer's dvorak. In this layout, I have to hold shift to type numbers. Almost all programs have no problem with that, but castle-editor is one of those programs that don't work well with this. Basically any input field on the right panel gets the wrong input when I try to type `(` - I get `1` instead (which is `Shift + (`). So it basically doesn't take input from Xorg which I use and map keyboard in, it seems?

Thanks.

**Comment by michaliskambi** [comment]
Thank you for the report! I want such feedback and I want to do a lot of "qualify of life" improvements to CGE editor already -- it has to be a comfortable tool to use.

> When a label (TCastleLabel) has no Caption and is autosized, hence no size, its position on screen is often reset to 0:0 when changing it or other components.

I cannot reproduce the problem now with a quick test, 

https://user-images.githubusercontent.com/1076978/207732402-f14f8d0d-8a43-4ab1-8c8e-694047d7e630.mp4

Can you describe (or create a video like above) when does the position on screen reset? I'd like to fix it.

> I use an unusual keyboard layout, programmer's dvorak.

Hm, as I don't use Dvorak. Can you do a little of experimenting to confirm/reject some possible causes?

Background: We have a hack to properly handle some keys that can serve as both edit keys (e.g. to type something) and menu item shortcuts. Like `1` which should cause typing `1` in the edit box, or invoke "front view" when no edit box is focused. It is a nasty hack and I really don't like it, but there's no choice (in LCL or even VCL) to do what we needed otherwise, see https://github.com/castle-engine/castle-engine/blob/master/tools/castle-editor/code/castlelcledithack.pas comments.

That said... the hack doesn't change the fact that we get keys from Xorg (from GTK 2 actually). We just apply some processing on them (that ideally we shouldn't have to do...). So I'm not sure does this cause trouble on Dvorak.

The code also has explicit condition to not do any change if you type a number with shift.

Can you experiment with compiling and testing your own editor? Follow "Compile the editor" from https://castle-engine.io/compiling_from_source.php .

Once you have your own editor, first of all confirm/reject the hypothesis that `CastleLclEditHack` is the culprit. To do this, edit `tools/castle-editor/code/formproject.pas` and in `TProjectForm.FormKeyDown` just comment out the call to `ProcessKeyToPerformEdit`. Then recompile the editor, and see if your problem is gone.

If the `CastleLclEditHack` is the culprit, please uncomment that `ProcessKeyToPerformEdit` call and debug what is received by `TEditBox.ProcessKey`, what `VK_xxx`, with what `Shift` state. This should explain what is happening and why it's wrong on Dvorak. You can alternatively play with example in https://github.com/michaliskambi/lcl-test-menu-special-shortcuts -- it has exactly the same `CastleLclEditHack` contents, but tests it in a simple project reporting various diagnostics.

**Comment by bbrtj** [comment]
Re first issue, empty label: Here's a video. As you can see, I can change anchor position when the label has caption and it stays where it is, but after I remove the label the translation gets reset to 0 after changing anchor. Same when drag&dropping the label on the hierarchy box on the left. Possibly in other scenarios as well, but can't remember right now.

https://user-images.githubusercontent.com/44323413/207778812-acd31b2f-3962-46ae-b1be-497f5b801657.mp4

**Comment by bbrtj** [comment]
Re second issue: luckily I compile CGE from sources anyway, so it was quick to test out. And yes, it helps... sort of.
I can now type special characters which in regular editor would input numbers, but some of these keys are now hijacked by the center viewport of the editor and change my point of view. For example, I can input `)` (with shift it's `2`, `8` on qwerty), but clicking `(` (with shift it's `1`, `5` on qwerty) changes viewport POV. So yes, `ProcessKeyToPerformEdit` is what causes the problem.

Note that you would not be able to reproduce this issue on regular dvorak, since it has numbers row the same as qwerty. You need programmer's dvorak specifically, if you want to test it then you most likely need to input this command: `setxkbmap -layout pl -variant dvp` (on Linux which uses xorg, the layout is preinstalled), unless something else in your system is managing your keymap, not xkb.

**Comment by bbrtj** [comment]
Here's a table of my testing of `Key` variable in `ProcessKeyToPerformEdit` procedure and results seen in the editor:
```
$ ~ $ ~ 148
& % & % 146
[ 7 [ 7 219
{ 5 5 5 53
} 3 3 3 51
( 1 1 1 49
= 9 9 9 57
* 0 0 0 48
) 2 2 2 50
+ 4 + 4 187
] 6 ] 6 221
! 8 8 8 56
# ` # ` 192
```

First two columns are just a listing of the top row on programmer's dvorak (without shift and with shift). Next two columns are what I see in the editor box when I press them (again, no shift / shift). The last column is the decimal keycode I get in the procedure. The `ssShift` state from `Shift` variable is correctly recognized.

Looking at the vk keycodes, it's quite obvious that they are very qwerty-centric, which is probably the bigger problem. I wouldn't be surprised if it was broken a couple levels up, not in CGE's control. However, as I said, the vast majority of applications handle my layout correctly and only some clever ones (like webapps which capture keys and don't let you enter non-numbers) are problematic.

**Comment by michaliskambi** [comment]
Sorry for the delay, I have a few big tasks to finish this week. And just yesterday we merged another big upgrade to Castle Game Engine physics (joints! documented briefly on https://castle-engine.io/physics ). I will get to this.

We talked with @and3md about the hack in our keys handling and we may have a better solution (deactivate menu items when focus is on an edit box). This would mean we *don't* try to process keys, and our edit boxes should behave the same as in other LCL applications.

**Comment by bbrtj** [comment]
Hey, just a bump, the first issue is still around (position resetting).

**Comment by michaliskambi** [comment]
Sorry for delay!

AD 1 - Thank you, fixed!

  After watching your movie and understanding the issue, this was the simplest thing to fix in the world, because I literally had to remove a line that was resetting the position to zero in this case in https://github.com/castle-engine/castle-engine/commit/828e783379fad4e3e33f45e69d90a0c23a797871 :)

AD 2 - Indeed, this issue is still present. 

  Our `CastleLclEditHack` is causing these problems. We should explore the idea to "deactivate menu items when focus is on an edit box" (it means dynamically changing key shortcuts depending on whether the edit has focus).
