### ISSUE TITLE
Check MouseRayHit over Tiled map

### ISSUE THREAD

**Issue by michaliskambi** [castle-engine/castle-engine#570]
Testcase: https://github.com/bbrtj/perl-mmo-game/ , @bbrtj reports it shows weird values , when map scale in Z is non-zero.

**Comment by michaliskambi** [comment]
P.S. If you want to avoid hitting the NPCs/actors by the `MouseRayHit`, you can 

1. Temporarily hide all the actors. 

    The easiest way to do this: have a parent TCastleTransform for all of them, like  `AllActorsParent:TCastleTransform`. Add all actors to it. You already add all actors using the line `FUIBoard.Parent.Add` in `TGameActorFactory.CreateActor`, so you'd just invent a new `AllActorsParent:TCastleTransform` and add actors to it. Once you have it, you can quickly hide all actors like `AllActorsParent.Exists:=false`.

2. Perform collision query using `MyViewport.PositionToRay` + `MyViewport.Items.WorldRay` instead of `MyViewport.MouseRayHit`. See https://castle-engine.io/tiled_maps#_general_case_any_camera_any_map_transformation for links. The `MyViewport.Items.WorldRay` returns `TRayCollision` so you can use with your existing `FindMapPosition`.

3. Afterwards, activate NPCs again like `AllActorsParent.Exists := true`.

**Comment by michaliskambi** [comment]
Last but not least, I have updated our docs about Tiled, how to determine tile indicated by mouse, to show `MouseRayHit.Info`. See https://castle-engine.io/tiled_maps#_general_case_any_camera_any_map_transformation .

**Comment by bbrtj** [comment]
Hey @michaliskambi, thanks a lot for figuring this out and the work you've done. Just for completeness, testing showed this part seems to be incorrect:

> My current proposed fix in PR https://github.com/bbrtj/perl-mmo-game/pull/1 means that clicking on an actor -- does nothing. Since actor is not a map.

I can click the actors and still get the proper XY coords. The log says `hit map: Board TCastleTiledMap at X:Y`, so seems like it detects the board anyway.

**Comment by michaliskambi** [comment]
> Just for completeness, testing showed this part seems to be incorrect:
> 
> >    My current proposed fix in PR https://github.com/bbrtj/perl-mmo-game/pull/1 means that clicking on an actor -- does nothing. Since actor is not a map.
> 
> I can click the actors and still get the proper XY coords. The log says hit map: Board TCastleTiledMap at X:Y, so seems like it detects the board anyway.

Hm, that's interesting. I didn't actually test my claim, but I was sure it will work like that -- since `MainViewport.MouseRayHit` returns the front-most TCastleTransform . So the `TGameActor` (descendant of `TCastleScene`) with large Z (in front of the map) should "obscure" the map at this point. And I see in code you don't tweak `Pickable` of any scene, so actors and maps should be detected the same by `MainViewport.MouseRayHit`.

From what I can see, your server is now offline. If you'd like to, you can make it online and I can investigate this, because it is interesting -- why we cannot pick the actors?

**Comment by michaliskambi** [comment]
Thank you -- I was scratching my head why it is happening, but I got it!

`PlayerCamera.Z` is `10` (`cCameraDistance`). But actors, after my PR, are at Z = `100`. 

Testing, indeed setting `cCameraDistance` to anything <= 99 means it doesn't detect actors, >= 101 means it does detect actors.

Explanation: The way `MouseRayHit` works, it shoots rays from the camera position. In case of orthographic projection it also matters, even the Z of camera matters. Even though we render things at any Z (because by default Camera.Orthographic.ProjectionNear is 0, which means "auto calculate", and internally it may even be auto calculated to a negative value -- ProjectionNear in 2D can be negative). 

But effectively, for typical 2D games, we only consider for `MouseRayHit` stuff that is at Z <= camera Z.

One can view it as a feature, since you get another way to control what is detected by `MouseRayHit`. But it's also unintuitive feature -- since the basic promise of `MouseRayHit` is to "detect what does the user see", and in this case this relation is broken. One can argue that `MouseRayHit` should account for projection near/far by default. If someone wants to query for a different Z, they can use `MyViewport.Items.WorldRay(...)` with any RayOrigin, maybe calculated using `MyViewport.PositionToRay` but with Z  tweaked.

OK, I have already in TODO to propose better API for mouse hitting. This is another thing I may decide to change in new API *or* at least document it more clearly.

You can take the server offline again, thank you -- we have the answers we need. Mystery solved, and I will not change how `MouseRayHit` works (to preserve compatibility), and I will think whether a new future API should be different with regards to this.

**Comment by bbrtj** [comment]
Thanks for the explanation. I find it a bit confusing that something with Z greater than camera Z (which is pointing down) is even visible on screen. Up to now I've been picking my Z-s in a way that would make stuff visible and in the right size. I guess I will have to learn more about orthographic projection :)
